server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework:
      security: TRACE
#    org.springframework.boot.autoconfigure: DEBUG

